[book]
title = "Zeebe Documentation"
description = "Zeebe is an orchestration engine for distributed microservices"

[output.html]
additional-css = ["custom.css"]
additional-js = ["highlight.protobuf.js"]
